export class DefaultValues {
  public static readonly PrivateKeyPem = `-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIL//YMwZwS233Q589Ug1btmvDxbQ2G5X4KoI6qt93b7/oAoGCCqGSM49AwEHoUQDQgAE5db4WYUrc8VhnmVPWLnUFfQryn8nDiWu92JZVle3w6NwnS/v4sOFyDIJguBrIceUeowDw8vweVXz3wu1pNUq4A==
-----END EC PRIVATE KEY-----`;

  public static readonly PublicKeyPem = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5db4WYUrc8VhnmVPWLnUFfQryn8nDiWu92JZVle3w6NwnS/v4sOFyDIJguBrIceUeowDw8vweVXz3wu1pNUq4A==
 -----END PUBLIC KEY-----`;

  public static readonly DSCPem = `-----BEGIN CERTIFICATE-----
MIICCTCCAa+gAwIBAgIUQ4CHxP8wPIcOT00z9CHO4EyG9mAwCgYIKoZIzj0EAwIwMzELMAkGA1UEBhMCR0IxEDAOBgNVBAgTB0VuZ2xhbmQxEjAQBgNVBAoTCVRlc3QgQ2VydDAeFw0yMjAxMjQyMDMzMTJaFw0yNDAxMTQyMDMzMTJaMDMxCzAJBgNVBAYTAkdCMRAwDgYDVQQIEwdFbmdsYW5kMRIwEAYDVQQKEwlUZXN0IENlcnQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATl1vhZhStzxWGeZU9YudQV9CvKfycOJa73YllWV7fDo3CdL+/iw4XIMgmC4Gshx5R6jAPDy/B5VfPfC7Wk1Srgo4GgMIGdMB0GA1UdDgQWBBTp+tzQ0Iu5/XyYRPftUGXFxMehWzBuBgNVHSMEZzBlgBTp+tzQ0Iu5/XyYRPftUGXFxMehW6E3pDUwMzELMAkGA1UEBhMCR0IxEDAOBgNVBAgTB0VuZ2xhbmQxEjAQBgNVBAoTCVRlc3QgQ2VydIIUQ4CHxP8wPIcOT00z9CHO4EyG9mAwDAYDVR0TBAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiAOfMgGPC7U8cPdXyWbERwX8BcWdCtc5QTNnNIu7LKGnAIhALhzHN6LTqkkVTC0Zjqdq2WM0dYqnTM3MSq2/kyNwGO/
-----END CERTIFICATE-----
    `;
}

export class Styles {
  public static readonly InputWidth = '400px';

  public static readonly PageWidth = '1000px';
}
