export const privateKeys: string[] = [
  `-----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIPyetiRiKTRijYTmnSesqX/Pu/PugMMzUQA+kSOgugDToAoGCCqGSM49
    AwEHoUQDQgAE70ce14enML4FZ5RbCNncw/+rdxwQWPWAnHW6XItqClCmZo2X4/Hm
    nzfxhOMFykKJx22kmTWsU4daRDN9voFhcw==
    -----END EC PRIVATE KEY-----
    `,
  `-----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMcS1wJt2pKm6pjW46NClLdn70YqNeqZoRcwiozT2jg4oAoGCCqGSM49
    AwEHoUQDQgAEOQDU+jHgUWFPswEJ78NXdN/8VkME3vlekzW688KOBseDtK4ytllk
    mu3e5o3nb61LE+01cNiNPcohh/GLCKYs7g==
    -----END EC PRIVATE KEY-----
    `,
  `-----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIDAM7kjf8X/TPudxnHMMfG9AA+61a290LbuyHmqot7RYoAoGCCqGSM49
    AwEHoUQDQgAE5wWvtgq3zHonTg80M1lwxTw9BO76Tt4WLRVt9XDY0n78mSZIuydF
    m3e/m1GMRKIfj5TLaZvDWqCg8MU87x5u0Q==
    -----END EC PRIVATE KEY-----`
];

export const publicCerts: string[] = [
  `-----BEGIN CERTIFICATE-----
    MIICeDCCAh6gAwIBAgIUanBjN55DXsiXgX017WlFrRj8JT8wCgYIKoZIzj0EAwIw
    VzELMAkGA1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGElu
    dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwMTAeFw0yMjA0
    MDgxNjM4MzZaFw0zMjAyMTUxNjM4MzZaMFcxCzAJBgNVBAYTAkdCMRMwEQYDVQQI
    EwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQx
    EDAOBgNVBAMTB2NlcnQgMDEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATvRx7X
    h6cwvgVnlFsI2dzD/6t3HBBY9YCcdbpci2oKUKZmjZfj8eafN/GE4wXKQonHbaSZ
    NaxTh1pEM32+gWFzo4HHMIHEMB0GA1UdDgQWBBQbMcfBysAW+tCMLs1sKwnBN7U7
    5zCBlAYDVR0jBIGMMIGJgBQbMcfBysAW+tCMLs1sKwnBN7U756FbpFkwVzELMAkG
    A1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGEludGVybmV0
    IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwMYIUanBjN55DXsiXgX01
    7WlFrRj8JT8wDAYDVR0TBAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEAlF4Gkz9c
    Loznw5Dx92h4fQ3PHOWWXGIse48jlpQm80ACIFQKqzlI/OTkKkonCBwbjMCpBfLE
    GH0gurHRXPZ6kXTD
    -----END CERTIFICATE-----
    `,
  `-----BEGIN CERTIFICATE-----
    MIICeDCCAh6gAwIBAgIUdDXaT+VgLpVrrlvE6CIqG25X/K0wCgYIKoZIzj0EAwIw
    VzELMAkGA1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGElu
    dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwMjAeFw0yMjA0
    MDgxNjM4NTRaFw0zMjAyMTUxNjM4NTRaMFcxCzAJBgNVBAYTAkdCMRMwEQYDVQQI
    EwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQx
    EDAOBgNVBAMTB2NlcnQgMDIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ5ANT6
    MeBRYU+zAQnvw1d03/xWQwTe+V6TNbrzwo4Gx4O0rjK2WWSa7d7mjedvrUsT7TVw
    2I09yiGH8YsIpizuo4HHMIHEMB0GA1UdDgQWBBRbnQCgzLKBM+zZEdYIOHsIu4uz
    cjCBlAYDVR0jBIGMMIGJgBRbnQCgzLKBM+zZEdYIOHsIu4uzcqFbpFkwVzELMAkG
    A1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGEludGVybmV0
    IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwMoIUdDXaT+VgLpVrrlvE
    6CIqG25X/K0wDAYDVR0TBAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiAKB9sbu90c
    N4Lt5JFn8dLeaUrFgRpSVsodCjwZWQSTrAIhAKTqugmkYaLn4L+xuphFLsF15gQu
    qaw6zJE7Z63Oc4zP
    -----END CERTIFICATE-----
    `,
  `-----BEGIN CERTIFICATE-----
    MIICeDCCAh6gAwIBAgIUUYDY10kpv8m4YItzA+7STli+sx4wCgYIKoZIzj0EAwIw
    VzELMAkGA1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGElu
    dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwMzAeFw0yMjA0
    MDgxNjM5MTBaFw0zMjAyMTUxNjM5MTBaMFcxCzAJBgNVBAYTAkdCMRMwEQYDVQQI
    EwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQx
    EDAOBgNVBAMTB2NlcnQgMDMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATnBa+2
    CrfMeidODzQzWXDFPD0E7vpO3hYtFW31cNjSfvyZJki7J0Wbd7+bUYxEoh+PlMtp
    m8NaoKDwxTzvHm7Ro4HHMIHEMB0GA1UdDgQWBBQYM9wSwcbMo0O6GOUjZRlhoq/v
    2TCBlAYDVR0jBIGMMIGJgBQYM9wSwcbMo0O6GOUjZRlhoq/v2aFbpFkwVzELMAkG
    A1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNVBAoTGEludGVybmV0
    IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAxMHY2VydCAwM4IUUYDY10kpv8m4YItz
    A+7STli+sx4wDAYDVR0TBAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEApthUH/Ix
    4gWPacvCEPh4TOa1yNMIQh+EZEpl/iTTrmECICE7ijo8dVlKf0CBGVlHbj2qN5ri
    oFPOJRLwPPUJAK08
    -----END CERTIFICATE-----
    `
];
